import type { AuthoredUnit } from "../../types"

export const u18: AuthoredUnit = {
  level: "N2", order: 18, title: "N2 capstone", titleJp: "Ｎ２ まとめ",
  description: "Review of the N2 system: formal connectors, keigo, conditions, and reading comprehension practice.",
  vocab: ["読解|どっかい", "筆者|ひっしゃ", "主張|しゅちょう", "論点|ろんてん", "根拠|こんきょ", "事実|じじつ", "解釈|かいしゃく", "要点|ようてん", "要約|ようやく", "一致|いっち", "矛盾|むじゅん", "結論|けつろん", "実力|じつりょく", "合格|ごうかく", "自信|じしん", "確かめる|たしかめる"],
  kanji: ["筆", "張", "論", "拠", "釈", "要", "約", "盾", "確"],
  exam: [
    { kind: "mcq", text: "Which pattern means 'no choice but to' (logical)?", options: ["〜あげく", "〜ざるを得ない", "〜おそれがある", "〜ばかりか"], answer: 1 },
    { kind: "mcq", text: "Which pattern is a formal risk warning?", options: ["〜に決まっている", "〜おそれがある", "〜っこない", "〜に限る"], answer: 1 },
  ],
  lessons: [
    { slug: "n2-u18-l01", title: "N2 grammar map", titleJp: "ぶんぽう まとめ", grammarLabel: "review",
      summary: "Six clusters: change, range, concession, obligation, likelihood, keigo.",
      body: { meaning: "N2 grammar clusters: (1) change につれて・に伴って・つつある・一方だ; (2) range にわたって・において・を問わず; (3) concession ものの・ながらも・にもかかわらず; (4) obligation ざるを得ない・ないわけにはいかない; (5) likelihood に違いない・おそれがある・はずがない; (6) keigo 尊敬語・謙譲語.",
        formation: [
          { pattern: "〜に伴って", note: "along with (formal)" },
          { pattern: "〜おそれがある", note: "risk of (warning)" },
          { pattern: "〜ざるを得ない", note: "can't help but (logic)" },
          { pattern: "〜に違いない", note: "must be (evidence)" },
        ],
        usage: ["These clusters cover most N2 exam questions.", "Keigo appears in both listening and reading sections."],
        pitfalls: ["おそれがある (risk) vs に違いない (certainty) — opposite ends.", "あげく (negative) vs 末(に) (neutral)."],
        related: ["u01-u17"] },
      examples: [
        { jp: "不況に伴って、失業率が上がりつつある。", kana: "ふきょうにともなって、しつぎょうりつがあがりつつある。", en: "Along with the recession, unemployment is steadily rising." },
        { jp: "彼が嘘をついたとは、信じざるを得ない。", kana: "かれがうそをついたとは、しんじざるをえない。", en: "I have no choice but to believe he lied." },
        { jp: "事故が再発するおそれがあるので、運転を中止します。", kana: "じこがさいはつするおそれがあるので、うんてんをちゅうしします。", en: "As there's a risk of another accident, we're halting operation." },
      ],
      practice: [
        { kind: "mcq", text: "Formal change marker →", options: ["につれて", "に伴って", "ように", "てから"], answer: 1 },
        { kind: "mcq", text: "Risk warning →", options: ["に違いない", "おそれがある", "はずがない", "っこない"], answer: 1 },
        { kind: "tf", text: "ざるを得ない is logic-driven; ずにはいられない is emotion-driven.", answer: true },
      ],
    },
    { slug: "n2-u18-l02", title: "Keigo recap + email practice", titleJp: "ビジネスメール", grammarLabel: "keigo review",
      summary: "Writing a business email: 拝啓・〜でございます・お手数ですが・何卒よろしくお願いいたします.",
      body: { meaning: "Business email skeleton: 拝啓 (Dear), お世話になっております (thank you for your support), お手数ですが (sorry to trouble you), 何卒よろしくお願いいたします (best regards).",
        formation: [
          { pattern: "お世話になっております。", note: "standard opener" },
          { pattern: "お手数ですが、ご確認をお願いいたします。", note: "polite request" },
          { pattern: "ご不明な点がございましたら、お知らせください。", note: "offer help" },
        ],
        usage: ["Fixed phrases are expected — don't improvise.", "Humble for self, honorific for client."],
        pitfalls: ["ございます/いたします are the keigo engine of emails.", "Don't use casual forms in email."],
        related: ["u16"] },
      examples: [
        { jp: "お世話になっております。田中でございます。", kana: "おせわになっております。たなかでございます。", en: "Thank you for your continued support. This is Tanaka." },
        { jp: "お手数ですが、ご確認のほどよろしくお願いいたします。", kana: "おてすうですが、ごかくにんのほどよろしくおねがいいたします。", en: "Sorry to trouble you, but please confirm." },
        { jp: "ご不明な点がございましたら、お気軽にお知らせください。", kana: "ごふめいなてんがございましたら、おきがるにおしらせください。", en: "If you have any questions, please let us know freely." },
      ],
      practice: [
        { kind: "mcq", text: "Standard business email opener:",
          options: ["やあ！", "お世話になっております。", "元気？", "さようなら"], answer: 1 },
        { kind: "mcq", text: "「お手数ですが」 introduces…",
          options: ["a complaint", "a polite request", "a joke", "a farewell"], answer: 1 },
        { kind: "tf", text: "いたします is the humble form of します.", answer: true },
      ],
    },
    { slug: "n2-u18-l03", title: "Reading comprehension strategy", titleJp: "どっかい さく", grammarLabel: "reading",
      summary: "Find 筆者 (author's) 主張 (claim) — keywords: しかし・つまり・要するに.",
      body: { meaning: "N2 reading strategy: the author's claim (主張) often follows signal words: しかし (contrast), つまり/要するに (in short), むしろ (rather).",
        formation: [
          { pattern: "しかし、〜", note: "however — the real point follows" },
          { pattern: "つまり、〜というわけだ", note: "in short — conclusion" },
          { pattern: "むしろ、〜というべきだ", note: "rather, it should be called" },
        ],
        usage: ["Questions ask 筆者はどう考えているか.", "Answer choices often paraphrase the claim."],
        pitfalls: ["Examples before しかし are setup, not the claim.", "Watch for double negation paraphrases."],
        related: ["u03", "u11"] },
      examples: [
        { jp: "多くの人が便利だと言う。しかし、筆者は逆の立場だ。", kana: "おおくのひとがべんりだという。しかし、ひっしゃはぎゃくのたちばだ。", en: "Many say it's convenient. However, the author takes the opposite view." },
        { jp: "つまり、技術そのものより使い方を考えるべきだというわけだ。", kana: "つまり、ぎじゅつそのものよりつかいかたをかんがえるべきだというわけだ。", en: "In short, we should think about usage rather than the technology itself." },
        { jp: "要するに、判断は事実に基づくべきだ。", kana: "ようするに、はんだんはじじつにもとづくべきだ。", en: "In a word, judgment should be based on facts." },
      ],
      practice: [
        { kind: "mcq", text: "The author's claim usually follows…", options: ["しかし", "例えば", "まず", "さらに"], answer: 0 },
        { kind: "mcq", text: "「つまり」 signals…", options: ["a new topic", "a conclusion", "a question", "an example"], answer: 1 },
        { kind: "tf", text: "「筆者はどう考えているか」 asks for the author's view.", answer: true },
      ],
    },
    { slug: "n2-u18-l04", title: "Final review + confidence", titleJp: "さいしゅう ふくしゅう", grammarLabel: "review",
      summary: "Mixed practice across all 18 units — then take the N2 exam.",
      body: { meaning: "Final mixed set: combine clusters and verify you can tell similar patterns apart: 上に (addition) vs 上で (sequence), あげく (negative) vs 末(に) (neutral), かねる (cannot) vs かねない (might).",
        formation: [
          { pattern: "〜上に", note: "addition" },
          { pattern: "〜上で", note: "after doing" },
          { pattern: "〜かねる／かねない", note: "cannot / might" },
        ],
        usage: ["Re-read units where you missed practice items.", "Then attempt the N2 exam and level exam."],
        pitfalls: ["Minimal pairs are the test's favourite trap.", "Register matters: casual vs written."],
        related: ["u01-u17", "N1 curriculum"] },
      examples: [
        { jp: "確認の上、ご返事いたします。", kana: "かくにんのうえ、ごへんじいたします。", en: "After confirming, I will reply." },
        { jp: "この店は安い上に、味もいい。", kana: "このみせはやすいうえに、あじもいい。", en: "This restaurant is cheap, and tasty on top of that." },
        { jp: "無断使用はお断りしかねます。", kana: "むだんしようはおこわりしかねます。", en: "We must decline unauthorized use." },
      ],
      practice: [
        { kind: "mcq", text: "Addition (both good) →", options: ["上で", "上に", "あげく", "かねる"], answer: 1 },
        { kind: "mcq", text: "Cannot bring oneself to →", options: ["かねない", "かねる", "上に", "末に"], answer: 1 },
        { kind: "tf", text: "あげく leans negative; 末(に) is neutral.", answer: true },
      ],
    },
  ],
}
