import type { AuthoredUnit } from "../../types"

export const u15: AuthoredUnit = {
  level: "N1", order: 15, title: "Fruits of labor", titleJp: "けっか と かち",
  description: "Worth and outcome: 〜に値する (worth), 〜に足る (review), 〜にたえない (review), 〜甲斐がある (worthwhile), 〜かいがある.",
  vocab: ["価値|かち", "評価|ひょうか", "信頼|しんらい", "名誉|めいよ", "努力|どりょく", "報いる|むくいる", "研究|けんきゅう", "読書|どくしょ", "賞|しょう", "受賞|じゅしょう", "作|さく", "後悔|こうかい", "満足|まんぞく", "達成|たっせい", "成果|せいか"],
  kanji: ["値", "誉", "頼", "賞", "読", "書", "悔", "満", "足"],
  exam: [
    { kind: "mcq", text: "「彼の業績は賞賛に値する。」 means…", options: ["His achievements deserve criticism.", "His achievements deserve praise.", "He refuses awards.", "Praise is forbidden."], answer: 1 },
    { kind: "mcq", text: "「十年間の研究の甲斐があって、ようやく特許が取れた。」 means…", options: ["The research was wasted.", "Ten years of research paid off — the patent finally came through.", "The patent was rejected.", "Research lasted one year."], answer: 1 },
  ],
  lessons: [
    { slug: "n1-u15-l01", title: "Worth: 〜に値する", titleJp: "〜に値する", grammarLabel: "〜に値する",
      summary: "に値する = worth X: 賞賛に値する.",
      body: { meaning: "Noun + に値する = DESERVES/WORTH X: 信頼に値する人物.", formation: [{ pattern: "Noun ＋ に値する", note: "賞賛に値する" }, { pattern: "〜に値しない", note: "not worth" }], usage: ["Formal evaluation.", "X = 賞賛・信頼・議論・検討."], pitfalls: ["値する is a suru-verb of value.", "Negative: に値しない."], related: ["〜に足る", "〜にたえない"] },
      examples: [
        { jp: "彼の業績は、賞賛に値する。", kana: "かれのぎょうせきは、しょうさんにあたいする。", en: "His achievements deserve praise." },
        { jp: "その提案は、検討に値する。", kana: "そのていあんは、けんとうにあたいする。", en: "That proposal is worth examining." },
        { jp: "うわさは、信頼に値しない。", kana: "うわさは、しんらいにあたいしない。", en: "The rumor isn't worth trusting." },
      ],
      practice: [
        { kind: "blank", text: "彼の業績は、賞賛___。", blanks: ["に値する"] },
        { kind: "mcq", text: "に値しない means…", options: ["very worthy", "not worth it", "must do", "cannot do"], answer: 1 },
        { kind: "tf", text: "に値する takes nouns like 賞賛・信頼.", answer: true },
      ],
    },
    { slug: "n1-u15-l02", title: "Worthwhile: 〜甲斐がある", titleJp: "〜甲斐がある", grammarLabel: "〜甲斐がある",
      summary: "甲斐がある = worth the effort: 生きた甲斐がある.",
      body: { meaning: "Verb た/る + 甲斐(かい)がある = IT WAS WORTH X: 努力した甲斐があった.", formation: [{ pattern: "Verb た ＋ 甲斐がある", note: "やった甲斐がある" }, { pattern: "Verb る ＋ 甲斐がある", note: "生きる甲斐がある" }, { pattern: "〜かいがあって", note: "adverbial" }], usage: ["Looking back on effort.", "Positive outcomes."], pitfalls: ["甲斐 = worth/effect.", "Negative: 甲斐がない (in vain)."], related: ["〜に値する", "〜だけのことはある (N2)"] },
      examples: [
        { jp: "十年間の研究の甲斐があって、特許が取れた。", kana: "じゅうねんかんのけんきゅうのかいがあって、とっきょがとれた。", en: "Ten years of research paid off — we got the patent." },
        { jp: "毎日の練習の甲斐があって、彼は優勝した。", kana: "まいにちのれんしゅうのかいがあって、かれはゆうしょうした。", en: "Daily practice paid off — he won." },
        { jp: "人を助ける仕事には、生きる甲斐を感じる。", kana: "ひとをたすけるしごとには、いきるかいをかんじる。", en: "In work that helps people, I feel life is worthwhile." },
      ],
      practice: [
        { kind: "blank", text: "十年間の研究の___があって、特許が取れた。", blanks: ["甲斐"] },
        { kind: "mcq", text: "甲斐がない means…", options: ["fruitful", "in vain", "dangerous", "free"], answer: 1 },
        { kind: "tf", text: "生きる甲斐 = one's reason for living.", answer: true },
      ],
    },
    { slug: "n1-u15-l03", title: "Not worth it: 〜にたえない (review) & 〜に足りない", titleJp: "ふそく の ぶんぽう", grammarLabel: "insufficiency",
      summary: "にたえない (unbearable/not worth) and に足りない (insufficient) — evaluation patterns.",
      body: { meaning: "Evaluation pair: 見るにたえない (too painful to watch) vs 問題にするに足りない (not worth making an issue of). Both deny worth.",
        formation: [
          { pattern: "Verb る ＋ にたえない", note: "unbearable to X" },
          { pattern: "Verb る ＋ に足りない", note: "insufficient for X" },
          { pattern: "Verb る ＋ に足る", note: "sufficient for X" },
        ],
        usage: ["たえない leans emotional; 足る leans logical sufficiency."],
        pitfalls: ["足る is classical; 値する is modern value talk."],
        related: ["〜に値する", "〜甲斐がある"] },
      examples: [
        { jp: "その映像は、見るにたえなかった。", kana: "そのえいぞうは、みるにたえなかった。", en: "The footage was too painful to watch." },
        { jp: "些細なミスは、問題にするに足りない。", kana: "ささいなミスは、もんだいにするにたりない。", en: "A trivial mistake isn't worth making an issue of." },
        { jp: "誇るに足る成果を残したい。", kana: "ほこるにたるせいかをのこしたい。", en: "I want to leave results worth being proud of." },
      ],
      practice: [
        { kind: "mcq", text: "見るにたえない = ?",
          options: ["worth watching", "too painful to watch", "watch again", "watch soon"], answer: 1 },
        { kind: "mcq", text: "問題にするに足りない = ?",
          options: ["make it an issue", "not worth the issue", "solve the issue", "raise the issue"], answer: 1 },
        { kind: "tf", text: "誇るに足る成果 = results sufficient to boast about.", answer: true },
      ],
    },
    { slug: "n1-u15-l04", title: "Reading: the researcher's pride", titleJp: "どっかい", grammarLabel: "reading",
      summary: "Value-evaluation patterns in a passage about research.",
      body: { meaning: "Passage: 「長年の研究が実り、名誉ある賞を受賞した。信頼に値するデータは、努力の甲斐を証明している。」",
        formation: [
          { pattern: "名誉ある賞を受賞", note: "received a prestigious award" },
          { pattern: "信頼に値するデータ", note: "data worth trusting" },
          { pattern: "努力の甲斐を証明", note: "proves the effort was worth it" },
        ],
        usage: ["Value talk clusters: 値する・足る・甲斐・名誉.", "JLPT loves these in author-intent questions."],
        pitfalls: ["名誉ある = honorable; 受賞 = receive award."],
        related: ["lessons 1-3"] },
      examples: [
        { jp: "長年の研究が実り、名誉ある賞を受賞した。", kana: "ちょうねんのけんきゅうがみのり、めいよあるしょうをじゅしょうした。", en: "Years of research bore fruit, and she received a prestigious award." },
        { jp: "信頼に値するデータは、努力の甲斐を証明している。", kana: "しんらいにあたいするデータは、どりょくのかいをしょうめいしている。", en: "Trustworthy data proves the effort was worth it." },
        { jp: "後悔にたえない失敗も、次の発見につながった。", kana: "こうかいにたえないしっぱいも、つぎのはっけんにつながった。", en: "Even the failure too painful to regret led to the next discovery." },
      ],
      practice: [
        { kind: "mcq", text: "「信頼に値するデータ」 means the data is…",
          options: ["fake", "trustworthy", "old", "missing"], answer: 1 },
        { kind: "mcq", text: "「努力の甲斐を証明」 means effort was…",
          options: ["wasted", "worthwhile", "short", "hidden"], answer: 1 },
        { kind: "tf", text: "受賞 means to receive an award.", answer: true },
      ],
    },
  ],
}
