import type { AuthoredUnit } from "../../types"

export const u17: AuthoredUnit = {
  level: "N1", order: 17, title: "Volition's edge", titleJp: "いし の ぶんぽう",
  description: "Refusal and possibility: 〜まい (won't/probably not), 〜かねない (review), 〜かねる (review), 〜得る/得ない (can/cannot conceivably).",
  vocab: ["二度と|にどと", "間違う|まちがう", "映像|えいぞう", "事実|じじつ", "主張|しゅちょう", "反論|はんろん", "証拠|しょうこ", "事故|じこ", "起きる|おきる", "危険|きけん", "想像|そうぞう", "理解|りかい", "納得|なっとく", "決定|けってい", "承諾|しょうだく", "断る|ことわる"],
  kanji: ["映", "像", "証", "拠", "論", "危", "険", "想", "得"],
  exam: [
    { kind: "mcq", text: "「二度と同じ過ちは繰り返すまいと決意した。」 — まい expresses…", options: ["strong intention not to repeat", "a wish to repeat", "past habit", "probability of repeating"], answer: 0 },
    { kind: "mcq", text: "「その光景は、想像に難くない。」 means…", options: ["It's hard to imagine.", "It's not difficult to imagine.", "It's forbidden to imagine.", "Nobody imagined it."], answer: 1 },
  ],
  lessons: [
    { slug: "n1-u17-l01", title: "Never again: 〜まい", titleJp: "〜まい", grammarLabel: "〜まい",
      summary: "まい = won't (strong resolve) / probably not: 二度と行くまい.",
      body: { meaning: "Verb + まい = STRONG NEGATIVE WILL (never again) or negative conjecture: 二度と失敗するまい.", formation: [{ pattern: "Verb る ＋ まい", note: "行くまい" }, { pattern: "する → しまい／すまい", note: "irregular" }], usage: ["Formal resolve or literary conjecture.", "Fixed: あるまいし (it's not as if…)."], pitfalls: ["る-verbs attach to dictionary form (unlike んばかり).", "あるまいし is a set phrase."], related: ["〜うと〜まいと (u06)", "〜ないつもりだ"] },
      examples: [
        { jp: "二度と同じ過ちは繰り返すまいと決意した。", kana: "にどとおなじあやまちはくりかえすまいとけっいした。", en: "I resolved never to repeat the same mistake." },
        { jp: "彼はもう帰るまいと心を決めた。", kana: "かれはもうかえるまいとこころをきめた。", en: "He made up his mind not to return again." },
        { jp: "プロであるまいし、完璧でなくてもいい。", kana: "プロであるまいし、かんぺきでなくてもいい。", en: "It's not as if you're a pro — no need for perfection." },
      ],
      practice: [
        { kind: "blank", text: "二度と同じ過ちは繰り返す___と決意した。", blanks: ["まい"] },
        { kind: "mcq", text: "する + まい = ", options: ["しまい／すまい", "せまい", "さしまい", "こまい"], answer: 0 },
        { kind: "tf", text: "あるまいし means 'it's not as if…'.", answer: true },
      ],
    },
    { slug: "n1-u17-l02", title: "Can conceivably: 〜得る／得ない", titleJp: "〜得る・〜得ない", grammarLabel: "〜得る／得ない",
      summary: "得る = can (conceivably) happen; 得ない = cannot: 起こり得る・あり得ない.",
      body: { meaning: "Verb ます-stem + 得る = CAN (conceivably) X: 十分あり得る. 得ない = CANNOT: 理解し得ない.", formation: [{ pattern: "Verb ます-stem ＋ 得る／得ない", note: "起こり得る" }, { pattern: "あり得ない", note: "impossible (very common)" }], usage: ["Logical possibility analysis.", "あり得る/あり得ない are everyday."], pitfalls: ["得る reads える; 得ない reads えない.", "ます-stem only."], related: ["〜ようがない (N2)", "〜かねない"] },
      examples: [
        { jp: "同じ事故は十分起こり得る。", kana: "おなじじこはじゅうぶんおこりうる。", en: "The same accident could very well happen." },
        { jp: "彼がそんなことをするのは、あり得ない。", kana: "かれがそんなことをするのは、ありえない。", en: "Him doing that is simply impossible." },
        { jp: "機械の誤作動は排除し得ない要因だ。", kana: "きかいのごさどうははいじょしえないよういんだ。", en: "Malfunctions are factors that cannot be eliminated." },
      ],
      practice: [
        { kind: "blank", text: "同じ事故は十分起こり___。", blanks: ["得る"] },
        { kind: "mcq", text: "あり得ない means…", options: ["likely", "impossible", "required", "recent"], answer: 1 },
        { kind: "tf", text: "得る attaches to the ます-stem.", answer: true },
      ],
    },
    { slug: "n1-u17-l03", title: "Might / cannot: かねない・かねる (review)", titleJp: "かねない・かねる", grammarLabel: "review",
      summary: "かねない = might (badly); かねる = cannot (polite refusal).",
      body: { meaning: "The pair in contrast: 台風次第で遅れかねない (might be late) vs ご承諾しかねます (we must decline).",
        formation: [
          { pattern: "Verb ます-stem ＋ かねない", note: "might (unwelcome)" },
          { pattern: "Verb ます-stem ＋ かねる", note: "cannot (refusal)" },
          { pattern: "いたしかねます", note: "set business phrase" },
        ],
        usage: ["かねない = risk; かねる = inability/refusal."],
        pitfalls: ["Same stem, opposite meanings.", "かねる is polite business refusals."],
        related: ["〜得る/得ない", "〜おそれがある (N2)"] },
      examples: [
        { jp: "無理な急行は、事故になりかねない。", kana: "むりなきゅうこうは、じこになりかねない。", en: "A reckless rush could easily cause an accident." },
        { jp: "規定外のご使用は、お受けいたしかねます。", kana: "きていがいのごしようは、おうけいたしかねます。", en: "We cannot accept use outside the terms." },
        { jp: "確認を怠れば、重大なミスを招きかねない。", kana: "かくにんをおこたれば、じゅうだいなミスをまねきかねない。", en: "Neglecting checks could invite serious mistakes." },
      ],
      practice: [
        { kind: "mcq", text: "事故になりかねない = ?",
          options: ["won't happen", "might well happen", "must happen", "happened already"], answer: 1 },
        { kind: "mcq", text: "いたしかねます = ?",
          options: ["we gladly will", "we must decline", "we might", "we did"], answer: 1 },
        { kind: "tf", text: "かねない and かねる take the same stem.", answer: true },
      ],
    },
    { slug: "n1-u17-l04", title: "Hard to imagine: 想像に難くない", titleJp: "そうぞう", grammarLabel: "reading",
      summary: "想像に難くない = not hard to imagine; literary logic phrases.",
      body: { meaning: "Editorial phrasing: 想像に難くない (not hard to imagine), 推測に難くない, 言うまでもない.",
        formation: [
          { pattern: "想像に難くない", note: "not difficult to imagine" },
          { pattern: "推測の余地はない", note: "no room for guesswork" },
          { pattern: "明白だ", note: "plain as day" },
        ],
        usage: ["Editorials use 難くない = not difficult (double negative)."],
        pitfalls: ["難くない = 難く + ない (classical く form)."],
        related: ["〜得る/得ない", "〜まい"] },
      examples: [
        { jp: "結果を目の前にして、彼の悔しさは想像に難くない。", kana: "けっかをまのにして、かれのくやしさはそうぞうにかたくない。", en: "Facing the results, his frustration is not hard to imagine." },
        { jp: "証拠が示す事実は、明白だ。", kana: "しょうこがしめすじじつは、めいはくだ。", en: "The facts the evidence shows are plain as day." },
        { jp: "この映像を見れば、主張の真偽は推測に難くない。", kana: "このえいぞうをみれば、しゅちょうのしんぎはすいそくにかたくない。", en: "Watch this footage, and the claim's truth is not hard to infer." },
      ],
      practice: [
        { kind: "mcq", text: "想像に難くない means…",
          options: ["impossible to imagine", "not hard to imagine", "must imagine", "don't imagine"], answer: 1 },
        { kind: "mcq", text: "難くない is a ___ negative.",
          options: ["single", "double", "future", "honorific"], answer: 1 },
        { kind: "tf", text: "明白だ means 'clear/obvious'.", answer: true },
      ],
    },
  ],
}
