import type { AuthoredUnit } from "../../types"

export const u19: AuthoredUnit = {
  level: "N1", order: 19, title: "Keigo mastery", titleJp: "けいご きゅうきゅう",
  description: "Advanced keigo: 謙譲語 II (伺う・申し上げる), special honorific verbs, double-keigo traps, and business email skeletons.",
  vocab: ["申し上げる|もうしあげる", "存じる|ぞんじる", "存じ上げる|ぞんじあげる", "拝借|はいしゃく", "頂戴|ちょうだい", "承る|うけたまわる", "ご容赦|ごようしゃ", "お手数|おてすう", "恐れ入ります|おそれいります", "ご多用|ごたぼう", "遺憾|いかん", "陳謝|ちんしゃ", "謹んで|つつしんで", "賜る|たまわる", "下さる|くださる", "いらっしゃる|いらっしゃる"],
  kanji: ["申", "上", "存", "借", "戴", "承", "赦", "謹", "賜"],
  exam: [
    { kind: "mcq", text: "「その件は承っております。」 — 承る means…", options: ["to refuse", "to accept/understand (humble)", "to forget", "to doubt"], answer: 1 },
    { kind: "mcq", text: "「ご多用のところ恐れ入りますが、ご確認ください。」 is…", options: ["a threat", "a polite request", "a complaint", "a farewell"], answer: 1 },
  ],
  lessons: [
    { slug: "n1-u19-l01", title: "Humble II: 申し上げる・存じ上げる", titleJp: "けんじょうご に", grammarLabel: "謙譲語 II",
      summary: "謙譲語 II ( respectful self-lowering toward the topic): 申し上げる・存じ上げる・承る・拝借する.",
      body: { meaning: "謙譲語 II lowers YOUR action toward the LISTENER-TOPIC (not the doer): 申す→申し上げる, 知る→存じ上げる, 聞く→承る, 借りる→拝借する.",
        formation: [
          { pattern: "言う → 申し上げる", note: "say (to a respected person)" },
          { pattern: "知る → 存じ上げる", note: "know (a person)" },
          { pattern: "聞く・受ける → 承る", note: "accept/understand" },
          { pattern: "借りる → 拝借する", note: "borrow" },
        ],
        usage: ["Extremely formal business/writing.", "Direction of respect matters more than the doer."],
        pitfalls: ["存じ上げる needs a person you know; 存じる for facts (存じません = don't know)."],
        related: ["謙譲語 I (N2 u16)", "尊敬語"] },
      examples: [
        { jp: "その件は、すでに承っております。", kana: "そのけんは、すでにうけたまわっております。", en: "We are already aware of the matter (and have accepted it)." },
        { jp: "先生には失礼を申し上げました。", kana: "せんせいにはしつれいをもうしあげました。", en: "I offered an apology to the teacher." },
        { jp: "辞書を拝借してもよろしいでしょうか。", kana: "じしょをはいしゃくしてもよろしいでしょうか。", en: "Might I borrow your dictionary?" },
      ],
      practice: [
        { kind: "match", text: "Match the humble II forms.", pairs: [["言う", "申し上げる"], ["知る(人)", "存じ上げる"], ["聞く", "承る"], ["借りる", "拝借する"]] },
        { kind: "mcq", text: "存じ上げます is used for…", options: ["facts", "knowing a person", "objects", "places only"], answer: 1 },
        { kind: "tf", text: "承る can mean both 'hear' and 'accept'.", answer: true },
      ],
    },
    { slug: "n1-u19-l02", title: "Honorific verbs: special forms", titleJp: "そんけいご とくべつけい", grammarLabel: "special honorifics",
      summary: "なさる・いらっしゃる・おっしゃる・ご覧になる — the four irregular honorifics.",
      body: { meaning: "Four special honorific verbs: する→なさる, 行く/来る/いる→いらっしゃる, 言う→おっしゃる, 見る→ご覧になる.",
        formation: [
          { pattern: "する → なさる → なさいます", note: "special ます form" },
          { pattern: "行く → いらっしゃる → いらっしゃいます", note: "same for 来る/いる" },
          { pattern: "言う → おっしゃる → おっしゃいます", note: "say" },
          { pattern: "見る → ご覧になる", note: "look/watch" },
        ],
        usage: ["For customers, teachers, seniors.", "Command: ご覧ください."],
        pitfalls: ["なさる→なさいます (not なさります); same for いらっしゃる/おっしゃる/くださる."],
        related: ["謙譲語 II", "丁寧語"] },
      examples: [
        { jp: "先生がいらっしゃいました。", kana: "せんせいがいらっしゃいました。", en: "The teacher has arrived." },
        { jp: "何もおっしゃいませんでした。", kana: "なにもおっしゃいませんでした。", en: "He said nothing at all." },
        { jp: "こちらをご覧ください。", kana: "こちらをごらんください。", en: "Please look at this." },
      ],
      practice: [
        { kind: "mcq", text: "Correct ます form of いらっしゃる:",
          options: ["いらっさります", "いらっしゃいます", "いらっしゃりいます", "いっしゃいます"], answer: 1 },
        { kind: "mcq", text: "「ご覧ください」 is a request for the listener to…",
          options: ["eat", "look", "listen", "leave"], answer: 1 },
        { kind: "tf", text: "おっしゃる → おっしゃいます (irregular ます form).", answer: true },
      ],
    },
    { slug: "n1-u19-l03", title: "Double keigo traps", titleJp: "ごいご", grammarLabel: "double keigo",
      summary: "Avoid 二重敬語: ×お読みになられる → ○お読みになる.",
      body: { meaning: "二重敬語 = stacking honorifics on one verb (×おっしゃられる). Exceptions: いらっしゃられる (acceptable), お食べになられる (avoid).",
        formation: [
          { pattern: "× お読みになられる", note: "double — use お読みになる" },
          { pattern: "× おっしゃられる", note: "double — use おっしゃる" },
          { pattern: "○ いらっしゃいました", note: "already honorific" },
        ],
        usage: ["Check one honorific layer per verb.", "Humble + honorific can coexist in a sentence (different subjects)."],
        pitfalls: ["ご説明させていただきます is overused — prefer ご説明します."],
        related: ["尊敬語", "謙譲語"] },
      examples: [
        { jp: "社長がお読みになりました。", kana: "しゃちょうがおよみになりました。", en: "The president read it (honorific, single layer)." },
        { jp: "私がご説明いたします。", kana: "わたしがごせつめいいたします。", en: "I will explain (humble, single layer)." },
        { jp: "お客様がお見えになりました。", kana: "おきゃくさまがおみえになりました。", en: "The customer has arrived." },
      ],
      practice: [
        { kind: "mcq", text: "Which is correct (no double keigo)?",
          options: ["お読みになられる", "お読みになる", "お読みなさられる", "読まれる"], answer: 1 },
        { kind: "mcq", text: "お見えになる means (honorific)…",
          options: ["to see something", "to arrive/come", "to eat", "to sleep"], answer: 1 },
        { kind: "tf", text: "Honorific and humble can coexist in one sentence.", answer: true },
      ],
    },
    { slug: "n1-u19-l04", title: "Business email skeleton", titleJp: "ビジネスメール", grammarLabel: "email",
      summary: "Full email template: 拝啓/お世話になっております → お手数ですが → ご容赦ください → 何卒よろしくお願い申し上げます.",
      body: { meaning: "N1 email fluency: 拝啓/敬具 (letters), お世話になっております (emails), お手数ですが (request), ご容赦ください (forgive), 何卒 (please), 申し上げます (say).",
        formation: [
          { pattern: "お世話になっております。", note: "email opener" },
          { pattern: "お手数をおかけしますが、ご対応のほどよろしくお願いいたします。", note: "request" },
          { pattern: "ご不便をおかけし、申し訳ございません。", note: "apology" },
          { pattern: "何卒よろしくお願い申し上げます。", note: "closing" },
        ],
        usage: ["Fixed chunks are expected and safe.", "何卒 elevates よろしく."],
        pitfalls: ["恐れ入りますが also introduces requests.", "Don't mix casual openers."],
        related: ["謙譲語 II", "N2 u18"] },
      examples: [
        { jp: "平素より大変お世話になっております。", kana: "へいそよりたいへんおせわになっております。", en: "Thank you always for your continued support." },
        { jp: "ご多用のところ恐れ入りますが、ご確認のほどお願い申し上げます。", kana: "ごたぼうのところおそれいりますが、ごかくにんのほどおねがいもうしあげます。", en: "Apologies for troubling you at a busy time — kindly confirm." },
        { jp: "ご不便をおかけし、誠に申し訳ございません。何卒ご容赦ください。", kana: "ごふべんをおかけし、まことにもうしわけございません。なんそごようしゃください。", en: "We apologize for the inconvenience. We ask for your understanding." },
      ],
      practice: [
        { kind: "order", text: "何卒／よろしく／お願い／申し上げます／。", tokens: ["何卒", "よろしく", "お願い", "申し上げます"] },
        { kind: "mcq", text: "「恐れ入りますが」 introduces…",
          options: ["a complaint", "a polite request", "a joke", "a threat"], answer: 1 },
        { kind: "tf", text: "拝啓/敬具 frame formal letters.", answer: true },
      ],
    },
  ],
}
