import type { AuthoredUnit } from "../../types"

export const u20: AuthoredUnit = {
  level: "N1", order: 20, title: "N1 capstone", titleJp: "Ｎ１ まとめ",
  description: "Review of the full N1 system: evaluation, concession, literary style, thresholds, and keigo — then the N1 exam.",
  vocab: ["主張|しゅちょう", "論点|ろんてん", "根拠|こんきょ", "妥当性|だとうせい", "信憑性|しんぴょうせい", "指摘|してき", "忠告|ちゅうこく", "革新|かくしん", "転換|てんかん", "該当|がいとう", "促進|そくしん", "対処|たいしょ", "運営|うんえい", "果たす|はたす", "遂げる|とげる", "目覚ましい|めざましい"],
  kanji: ["張", "論", "妥", "憑", "指", "革", "換", "該", "当"],
  exam: [
    { kind: "mcq", text: "Which pattern means 'nothing more than'?", options: ["〜にほかならない", "〜にすぎない", "〜に至るまで", "〜をもって"], answer: 1 },
    { kind: "mcq", text: "Which pattern is a formal threshold marker?", options: ["〜ものを", "〜ともなると", "〜ことだ", "〜まい"], answer: 1 },
  ],
  lessons: [
    { slug: "n1-u20-l01", title: "N1 grammar map", titleJp: "ぶんぽう まとめ", grammarLabel: "review",
      summary: "Six clusters: evaluation, concession, emotion, sequence, scale, keigo.",
      body: { meaning: "N1 clusters: (1) evaluation にすぎない・に値する・に足る・甲斐; (2) concession とはいえ・にしろ・からといって; (3) emotion の至りだ・かぎりだ・を禁じ得ない・に堪えない; (4) sequence が早いか・や否や・そばから; (5) scale ともなると・に至っては・に至るまで; (6) keigo 謙譲語 II・二重敬語.",
        formation: [
          { pattern: "〜にすぎない", note: "merely" },
          { pattern: "〜とはいえ", note: "granted that" },
          { pattern: "〜を禁じ得ない", note: "cannot suppress" },
          { pattern: "〜や否や", note: "the instant" },
          { pattern: "〜に至るまで", note: "all the way to" },
        ],
        usage: ["These cover most N1 exam items.", "Register discrimination is the core skill."],
        pitfalls: ["Minimal pairs: にすぎない vs にほかならない.", "Literary vs spoken: ゆえに・ごとく・まい."],
        related: ["u01-u19"] },
      examples: [
        { jp: "彼の貢献は、単なる努力にすぎないとは言えない。", kana: "かれのこうけんは、たんなるどりょくにすぎないとはいえない。", en: "His contribution cannot be called mere effort." },
        { jp: "春とはいえ、まだ冷え込む日が続く。", kana: "はるとはいえ、まだひえこむひがつづく。", en: "Spring though it is, chilly days still continue." },
        { jp: "支援は全国に至るまで届いた。", kana: "しえんはぜんこくにいたるまでとどいた。", en: "The support reached every corner of the country." },
      ],
      practice: [
        { kind: "mcq", text: "Merely →", options: ["にほかならない", "にすぎない", "に至るまで", "をもってしても"], answer: 1 },
        { kind: "mcq", text: "The instant (newsy) →", options: ["そばから", "や否や", "ものを", "ことだ"], answer: 1 },
        { kind: "tf", text: "N1's core skill is choosing the right register.", answer: true },
      ],
    },
    { slug: "n1-u20-l02", title: "Literary voice", titleJp: "ぶんごう", grammarLabel: "literary",
      summary: "The literary toolkit: ゆえに・ごとく・まい・ものを・ことか — the written voice of N1.",
      body: { meaning: "Literary markers: ゆえに (because), ごとく (like), まい (won't), ものを (if only), ことか (how ever so). These give prose its 'author voice'.",
        formation: [
          { pattern: "〜ゆえに", note: "because of (formal)" },
          { pattern: "〜ごとく", note: "like (simile)" },
          { pattern: "〜まい", note: "negative volition" },
          { pattern: "〜ものを", note: "trailing regret" },
        ],
        usage: ["N1 reading passages lean on these.", "Don't use them in casual chat."],
        pitfalls: ["ごとき is attributive; ごとく adverbial.", "まい attaches to dictionary form for る-verbs."],
        related: ["u06", "u08", "u16"] },
      examples: [
        { jp: "弱さゆえに、人は学び続ける。", kana: "よわさゆえに、ひとはまなびつづける。", en: "Precisely because we are weak, we keep learning." },
        { jp: "時は水のごとく流れる。", kana: "ときはみずのごとくながれる。", en: "Time flows like water." },
        { jp: "もう迷うまいと心に誓った。", kana: "もうまようまいとこころにちかった。", en: "I swore to my heart never to waver again." },
      ],
      practice: [
        { kind: "mcq", text: "Because of (literary) →", options: ["から", "ゆえに", "ので", "ものを"], answer: 1 },
        { kind: "mcq", text: "Attributive simile →", options: ["ごとく", "ごとき", "まい", "ことか"], answer: 1 },
        { kind: "tf", text: "ものを trails off in regret.", answer: true },
      ],
    },
    { slug: "n1-u20-l03", title: "Reading: the editorial", titleJp: "しゃかい てんぼう", grammarLabel: "reading",
      summary: "Full editorial passage — identify claims, concessions, and evaluation language.",
      body: { meaning: "Editorial excerpt: 「技術の進歩は目覚ましい。とはいえ、効果の検証なくして、導入を急ぐべきではない。信頼に値するデータをもとに、慎重に判断すべきだろう。」",
        formation: [
          { pattern: "目覚ましい", note: "remarkable" },
          { pattern: "〜なくして〜ない", note: "without X, no Y" },
          { pattern: "信頼に値する", note: "worth trusting" },
          { pattern: "〜をもとに", note: "based on" },
        ],
        usage: ["Identify 主張 (claim): judge cautiously with good data.", "Concessions mark where the claim bends."],
        pitfalls: ["とはいえ concedes, then redirects.", "なくして is literary なしで."],
        related: ["u01", "u04", "u15"] },
      examples: [
        { jp: "技術の進歩は目覚ましい。", kana: "ぎじゅつのしんぽはめざましい。", en: "Technological progress is remarkable." },
        { jp: "とはいえ、効果の検証なくして、導入を急ぐべきではない。", kana: "とはいえ、こうかのけんしょうなくして、どうにゅうをいそぐべきではない。", en: "Even so, without verifying effects, we shouldn't rush adoption." },
        { jp: "信頼に値するデータをもとに、慎重に判断すべきだろう。", kana: "しんらいにあたいするデータをもとに、しんちょうにはんだんすべきだろう。", en: "We should judge cautiously based on data worth trusting." },
      ],
      practice: [
        { kind: "mcq", text: "The author's claim is…",
          options: ["adopt tech fast", "verify effects first, adopt cautiously", "reject all tech", "trust rumors"], answer: 1 },
        { kind: "mcq", text: "「〜なくして」 is the literary form of…",
          options: ["によって", "なしで", "にとって", "について"], answer: 1 },
        { kind: "tf", text: "とはいえ concedes the previous point.", answer: true },
      ],
    },
    { slug: "n1-u20-l04", title: "The road beyond", titleJp: "そのさきへ", grammarLabel: "finale",
      summary: "Final mixed practice — then the N1 exam, and where to go next.",
      body: { meaning: "You've covered 80 lessons from N5 to N1. Final tips: distinguish register first, then meaning; read daily; keep SRS reviews due-zero.",
        formation: [
          { pattern: "Register → meaning → form", note: "the answering order" },
          { pattern: "Minimal pairs to recheck", note: "上に/上で, あげく/末に, かねる/かねない" },
          { pattern: "Keep reviewing", note: "SRS due-zero daily" },
        ],
        usage: ["Revisit units you missed.", "Then take the N1 exam and level exam."],
        pitfalls: ["Don't cram — space it out.", "Output practice: write one paragraph daily."],
        related: ["u01-u19", "/dictionary", "/vocab"] },
      examples: [
        { jp: "学んだ文法を使って、日記を書いてみよう。", kana: "まなんだぶんぽうをつかって、にっきをかいてみよう。", en: "Try writing a diary using the grammar you've learned." },
        { jp: "辞書で言葉を調べる習慣は、一生の財産だ。", kana: "じしょでことばをしらべるしゅうかんは、いっしょうのざいさんだ。", en: "The habit of looking up words is a lifelong asset." },
        { jp: "毎日少しの積み重ねが、大きな力になる。", kana: "まいにちすこしのつみかさねが、おおきなちからになる。", en: "A little each day builds great strength." },
      ],
      practice: [
        { kind: "mcq", text: "Answer order for similar patterns:",
          options: ["form → register → meaning", "register → meaning → form", "meaning only", "form only"], answer: 1 },
        { kind: "tf", text: "Cannot bring oneself to → かねる; might badly → かねない.", answer: true },
        { kind: "tf", text: "上に adds; 上で sequences.", answer: true },
      ],
    },
  ],
}
