import type { AuthoredUnit } from "../../types"

export const u10: AuthoredUnit = {
  level: "N3", order: 10, title: "Risky business", titleJp: "きけんせいの ひょうげん",
  description: "Formal possibility and impossibility: 〜かねない (might well), 〜かねる (cannot quite), 〜恐れがある (there is a risk that).",
  vocab: ["事故|じこ", "危険|きけん", "影響|えいきょう", "問題|もんだい", "対応|たいおう", "承諾|しょうだく", "賛成|さんせい", "状況|じょうきょう", "防ぐ|ふせぐ", "起きる|おきる", "晚|ばん", "遅刻|ちこく", "遅れる|おくれる", "確認|かくにん", "結果|けっか", "判断|はんだん"],
  kanji: ["肯", "否", "承諾", "恐", "危険", "事故", "判断", "確認"],
  exam: [
    { kind: "mcq", text: "「このままでは事故が起きかねない。」 means…", options: ["An accident won't happen.", "An accident might well happen.", "An accident has already happened.", "We can prevent accidents."], answer: 1 },
  ],
  lessons: [
    { slug: "n3-u10-l01", title: "Might well happen", titleJp: "〜かねない", grammarLabel: "〜かねない",
      summary: "Negative outcome is POSSIBLE: 雨が降りかねない (it might well rain).",
      body: { meaning: "Verb ます-stem + かねない = a NEGATIVE outcome could easily happen. かねない literally means 'cannot be excluded'. Always implies something bad.",
        formation: [{ pattern: "Verb ます-stem ＋ かねない", note: "起こりかねない might happen" }],
        usage: ["Always negative/warning.", "Formal — news, warnings, reports."],
        pitfalls: ["Not for positive outcomes (✗ 合格しかねない).", "Stronger than かもしれません."],
        related: ["〜恐れがある (formal version)"] },
      examples: [
        { jp: "このままでは事故が起きかねない。", kana: "このままではじこがおきかねない。", en: "If this continues, an accident might well happen." },
        { jp: "彼の発言は誤解を招きかねない。", kana: "かれのはつげんはごかいをまねきかねない。", en: "His remarks could easily cause misunderstanding." },
        { jp: "油断すると大きなミスをしかねません。", kana: "ゆだんするとおおきなミスをしかねません。", en: "If you let your guard down, you might well make a big mistake." },
      ],
      practice: [
        { kind: "blank", text: "このままでは事故が起き___。", blanks: ["かねない"] },
        { kind: "mcq", text: "かねない is used for…", options: ["positive outcomes", "negative risks", "neutral facts", "questions"], answer: 1 },
        { kind: "tf", text: "かねない is stronger than かもしれない.", answer: true },
      ],
    },
    { slug: "n3-u10-l02", title: "Cannot quite", titleJp: "〜かねる", grammarLabel: "〜かねる",
      summary: "Polite refusal: いたしかねます (I'm afraid I cannot).",
      body: { meaning: "Verb ます-stem + かねる = unable to do something due to duty/circumstance. Very polite refusal — business Japanese.",
        formation: [{ pattern: "Verb ます-stem ＋ かねます", note: "いたしかねます" }],
        usage: ["Formal — business emails, customer service.", "Softer than できません but still a refusal."],
        pitfalls: ["〜かねる and 〜かねない are OPPOSITE meanings!", "かねる = cannot; かねない = might well."],
        related: ["〜かねない", "〜できません"] },
      examples: [
        { jp: "その件についてはお答えいたしかねます。", kana: "そのけんについてはこたえいたしかねます。", en: "I'm afraid I cannot answer that question." },
        { jp: "現時点では賛成しかねます。", kana: "げんじてんではさんせいしかねます。", en: "At this point, I'm afraid I cannot agree." },
        { jp: "その要求には応じかねます。", kana: "そのようきゅうにはおうじかねます。", en: "I'm afraid we cannot comply with that request." },
      ],
      practice: [
        { kind: "blank", text: "その件についてはお答えいた___ます。", blanks: ["しかね"] },
        { kind: "mcq", text: "かねる is used for…", options: ["positive predictions", "polite refusal", "casual chat", "commands"], answer: 1 },
        { kind: "tf", text: "〜かねる and 〜かねない have opposite meanings.", answer: true },
      ],
    },
    { slug: "n3-u10-l03", title: "There is a risk", titleJp: "〜おそれがある", grammarLabel: "〜恐れがある",
      summary: "Formal risk: 大雨洪水の恐れがある (there is a risk of flooding).",
      body: { meaning: "Verb plain + 恐れがある = there is a RISK/FEAR of a negative outcome. Very formal — weather reports, official warnings.",
        formation: [{ pattern: "Verb plain ＋ 恐れがある", note: "おそれがある" }, { pattern: "Noun の ＋ 恐れがある", note: "事故のおそれ" }],
        usage: ["Official announcements, news, weather reports.", "Always negative outcome."],
        pitfalls: ["Most formal of the three (かねない < 恐れがある).", "The noun version uses の: 事故のおそれ."],
        related: ["〜かねない", "〜かもしれません"] },
      examples: [
        { jp: "大雨により、洪水の恐れがあります。", kana: "おおあめにより、こうずいのおそれがあります。", en: "Due to heavy rain, there is a risk of flooding." },
        { jp: "この装置は爆発する恐れがある。", kana: "このそうちはばくはつするおそれがある。", en: "This device has a risk of exploding." },
        { jp: "経済の悪化により、失業率が上がる恐れがある。", kana: "けいざいのあっかにより、しつぎょうりつがあがるおそれがある。", en: "Due to economic deterioration, there is a risk of rising unemployment." },
      ],
      practice: [
        { kind: "blank", text: "大雨により、洪水の___があります。", blanks: ["恐れ"] },
        { kind: "mcq", text: "恐れがある is used in…", options: ["casual chat", "official warnings", "questions", "greetings"], answer: 1 },
        { kind: "tf", text: "恐れがある is the most formal risk expression.", answer: true },
      ],
    },
    { slug: "n3-u10-l04", title: "Risk expressions compared", titleJp: "きけんの まとめ", grammarLabel: "risk summary",
      summary: "かねない (might well), かねる (cannot), 恐れがある (formal risk) — never mix them up.",
      body: { meaning: "Three risk tools: かねない (might happen — bad), かねる (cannot do — polite refusal), 恐れがある (there is a risk — formal).",
        formation: [
          { pattern: "〜かねない", note: "might well (negative)" },
          { pattern: "〜かねる", note: "cannot quite (polite)" },
          { pattern: "〜恐れがある", note: "formal risk" },
        ],
        usage: ["かねない = warning; かねる = refusal; 恐れがある = announcement."],
        pitfalls: ["かねる and かねない look similar but mean OPPOSITE things.", "恐れがある is the most formal."],
        related: ["lessons 1-3"] },
      examples: [
        { jp: "不注意から事故が起きかねない。", kana: "ふちゅういからじこがおきかねない。", en: "An accident might well happen from carelessness." },
        { jp: "ご要望には応じかねます。", kana: "ごようぼうにはおうじかねます。", en: "I'm afraid we cannot meet your request." },
        { jp: "台風の接近により、浸水の恐れがあります。", kana: "たいふうのせっきんにより、しんすいのおそれがあります。", en: "Due to the typhoon approaching, there is a risk of flooding." },
      ],
      practice: [
        { kind: "mcq", text: "An accident MIGHT happen →", options: ["起きかねる", "起きかねない", "起きる恐れをします", "起きよう"], answer: 1 },
        { kind: "mcq", text: "I CANNOT agree →", options: ["賛成しかねない", "賛成しかねます", "賛成の恐れがある", "賛成でしょう"], answer: 1 },
        { kind: "match", text: "Match to nuance:", pairs: [["かねない", "might well (bad)"], ["かねる", "cannot (polite)"], ["恐れがある", "formal risk"]] },
        { kind: "tf", text: "かねない and かねる are the opposite.", answer: true },
      ],
    },
  ],
}
