import type { AuthoredUnit } from "../../types"

export const u16: AuthoredUnit = {
  level: "N3", order: 16, title: "N3 capstone", titleJp: "Ｎ３ まとめ",
  description: "Review of the N3 grammar system: passives, causatives, giving/receiving, conditions, speculation, concession, and formal layering.",
  vocab: ["復習|ふくしゅう", "理解|りかい", "応用|おうよう", "練習|れんしゅう", "自信|じしん", "正解|せいかい", "間違い|まちがい", "文章|ぶんしょう", "文法|ぶんぽう", "語彙|ごい", "会話|かいわ", "工夫|くふう", "合格|ごうかく", "実力|じつりょく"],
  kanji: ["総", "復", "習", "解", "応", "自", "信", "合"],
  exam: [
    { kind: "mcq", text: "Which pattern stacks TWO GOOD (or two bad) things?", options: ["〜上で", "〜上に", "〜からこそ", "〜わけだ"], answer: 1 },
    { kind: "mcq", text: "Which pattern means 'no wonder'?", options: ["〜ものだ", "〜わけだ", "〜ものがある", "〜わりに"], answer: 1 },
  ],
  lessons: [
    { slug: "n3-u16-l01", title: "Core N3 grammar recap", titleJp: "ぶんぽう の ふくしゅう", grammarLabel: "review",
      summary: "Six pillars: purpose/cause, conditions, speculation, concession, appearance, formal layering.",
      body: { meaning: "N3 grammar clusters: (1) purpose & cause ために・ように・おかげで・せいで; (2) condition ば・たら・なら・さえ〜ば; (3) speculation はずだ・に違いない・かもしれない; (4) concession のに・くせに・にもかかわらず; (5) appearance らしい・っぽい・げ; (6) layering 上に・上で.",
        formation: [
          { pattern: "ように", note: "aim so that (hope)" },
          { pattern: "おかげで／せいで", note: "thanks to / because of (blame)" },
          { pattern: "はずだ", note: "should be (logic)" },
          { pattern: "にもかかわらず", note: "despite (formal)" },
          { pattern: "〜上に", note: "on top of" },
        ],
        usage: ["These 6 clusters cover most N3 exam questions.", "Each unit in this level has the full notes."],
        pitfalls: ["おかげで = good cause; せいで = bad cause.", "はずだ = logical expectation; わけだ = explanation."],
        related: ["u01-u15"] },
      examples: [
        { jp: "君が手伝ってくれたおかげで、間に合った。", kana: "きみがてつだってくれたおかげで、まにあった。", en: "Thanks to your help, I made it in time." },
        { jp: "熱があるのだから、今日は休むべきだ。", kana: "ねつがあるのだから、きょうはやすむべきだ。", en: "Since you have a fever, you should rest today." },
        { jp: "忙しい上に、風邪もひいた。", kana: "いそがしいうえに、かぜもひいた。", en: "I was busy, and caught a cold on top of that." },
      ],
      practice: [
        { kind: "mcq", text: "Bad cause →", options: ["おかげで", "せいで", "ために", "ように"], answer: 1 },
        { kind: "mcq", text: "Logical expectation →", options: ["わけだ", "はずだ", "ものだ", "わりに"], answer: 1 },
        { kind: "tf", text: "にもかかわらず is formal concession.", answer: true },
      ],
    },
    { slug: "n3-u16-l02", title: "Give and receive recap", titleJp: "あげる・くれる・もらう", grammarLabel: "review",
      summary: "あげる/くれる/もらう + their causative/te-form compounds.",
      body: { meaning: "The giving system: あげる (I give to others), くれる (someone gives to me), もらう (I receive). Te-form + あげる/くれる/もらう = doing a favour for someone.",
        formation: [
          { pattern: "〜てあげる", note: "do a favour for someone else" },
          { pattern: "〜てくれる", note: "they do a favour for me" },
          { pattern: "〜てもらう", note: "I get someone to do something" },
          { pattern: "〜ていただく／くださる", note: "polite versions" },
        ],
        usage: ["Choice depends on WHO benefits — くれる/もらう involve the speaker.", "Te-form + もらう = requesting action."],
        pitfalls: ["あげる to superiors = さしあげる.", "Never use あげる for things done TO the speaker."],
        related: ["N4 giving/receiving units"] },
      examples: [
        { jp: "先生に教えていただきました。", kana: "せんせいにおしえていただきました。", en: "I had the teacher teach me (humble)." },
        { jp: "友達が荷物を運んでくれた。", kana: "ともだいがにもつをはこんでくれた。", en: "A friend carried my luggage for me." },
        { jp: "彼に手伝ってもらいました。", kana: "かれにてつだってもらいました。", en: "I got him to help me." },
      ],
      practice: [
        { kind: "mcq", text: "Someone did something for the speaker →",
          options: ["〜てあげる", "〜てくれる", "〜てもらう", "〜てしまう"], answer: 1 },
        { kind: "mcq", text: "The most humble receiving form is…",
          options: ["もらう", "いただく", "くださる", "あげる"], answer: 1 },
        { kind: "tf", text: "てあげる implies the speaker is doing the favour.", answer: true },
      ],
    },
    { slug: "n3-u16-l03", title: "Passive & causative recap", titleJp: "じどう・うけみ", grammarLabel: "review",
      summary: "Passive れる/られる, causative せる/させる, causative-passive せられる.",
      body: { meaning: "Voice changes: passive (receiving an action), causative (making someone do), causative-passive (being forced to do). Key for formal writing and complaints.",
        formation: [
          { pattern: "Passive: れる／られる", note: "言われる be told" },
          { pattern: "Causative: せる／させる", note: "言わせる make say" },
          { pattern: "Causative-passive: せられる", note: "行かせられる be made to go" },
        ],
        usage: ["Passive = victim emphasis; causative = authority.", "Causative-passive = unwilling action (kids, jobs)."],
        pitfalls: ["き verbs → かされる: 書かされる.", "Passive+てもらう is rare."],
        related: ["N4 passive/causative units"] },
      examples: [
        { jp: "部長に残業させられた。", kana: "ぶちょうにざんぎょうさせられた。", en: "I was made to work overtime by my boss." },
        { jp: "弟は母に宿題をさせられた。", kana: "おとうとははかにしゅくだいをさせられた。", en: "My little brother was made to do his homework by my mother." },
        { jp: "この小説は多くの人に読まれている。", kana: "このしょうせつはおおくのひとによまれている。", en: "This novel is read by many people." },
      ],
      practice: [
        { kind: "mcq", text: "行かせられる means…",
          options: ["I let them go", "I was made to go", "they go", "we go"], answer: 1 },
        { kind: "mcq", text: "The causative-passive of 書く is…",
          options: ["書かれる", "書かせられる", "書かせる", "書ける"], answer: 1 },
        { kind: "tf", text: "Causative-passive often implies unwillingness.", answer: true },
      ],
    },
    { slug: "n3-u16-l04", title: "Reading: real-world paragraph", titleJp: "どっかい れんしゅう", grammarLabel: "reading",
      summary: "A paragraph using many N3 patterns at once — read and comprehend.",
      body: { meaning: "Real text combines patterns: 「多くの人は、時間がないと言う。しかし、計画を立てた上で行動すれば、意外と時間は作れるものだ。忙しいからこそ、工夫が必要なわけだ。」",
        formation: [
          { pattern: "〜と言う", note: "people say X" },
          { pattern: "〜上で", note: "after doing X" },
          { pattern: "〜ものだ", note: "naturally, people can…" },
          { pattern: "〜からこそ", note: "precisely because" },
          { pattern: "〜わけだ", note: "no wonder / it follows" },
        ],
        usage: ["Try to identify each grammar point as you read.", "This paragraph is JLPT N3 reading-section style."],
        pitfalls: ["しかし = however — signals a contrast.", "意外と = unexpectedly."],
        related: ["lessons 1-3", "u01-u15"] },
      examples: [
        { jp: "多くの人は、時間がないと言う。しかし、計画を立てた上で行動すれば、意外と時間は作れるものだ。", kana: "おおくのひとは、じかんがないという。しかし、けいかくをたてたうえでこうどうすれば、いがいとじかんはつくれるものだ。", en: "Many people say they have no time. However, if you act after making a plan, you can naturally find time after all." },
        { jp: "忙しいからこそ、工夫が必要なわけだ。", kana: "いそがしいからこそ、くふうがひつようなわけだ。", en: "It's precisely because we're busy that creativity is needed — that's the logic." },
        { jp: "文法を理解した上で、長文を読むと、意味がよくわかる。", kana: "ぶんぽうをりかいしたうえで、ちょうぶんをよむと、いみがよくわかる。", en: "After understanding the grammar, when you read long passages, the meaning becomes clear." },
      ],
      practice: [
        { kind: "mcq", text: "「意外と時間は作れるものだ」 — what does ものだ convey?",
          options: ["obligation", "natural tendency", "speculation", "concession"], answer: 1 },
        { kind: "mcq", text: "「忙しいからこそ、工夫が必要なわけだ」 — わけだ = ?",
          options: ["general truth", "logical conclusion", "impression", "obligation"], answer: 1 },
        { kind: "tf", text: "しかし signals a contrast.", answer: true },
      ],
    },
  ],
}
