// Seeds authored curriculum content into the database.
// Vocab is authored as "kanji|kana" strings resolved via content/vocab-index.json
// (generated by scripts/export-vocab-index.ts).
// Run: npx tsx scripts/seed-curriculum.ts
import { readFileSync } from "node:fs"

import { toRomaji } from "wanakana"

import { CURRICULUM } from "../content/curriculum"
import { AuthoredUnitSchema, type AuthoredQuestion, type AuthoredUnit, type Level } from "../content/types"
import { alignFurigana } from "../lib/furigana"
import type { QuizOption, QuizQuestion } from "../lib/quiz"
import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

type IndexEntry = { id: string; kana: string; kanji: string; gloss: string; level: number; pos: string[] }
const VOCAB_INDEX: Record<string, IndexEntry> = JSON.parse(
  readFileSync(new URL("../content/vocab-index.json", import.meta.url), "utf8"),
)

function resolveVocab(keys: string[], unitId: string): IndexEntry[] {
  return keys.map((key) => {
    const entry = VOCAB_INDEX[key]
    if (!entry) console.warn(`[vocab] ${unitId}: "${key}" not in vocab index — skipped`)
    return entry
  }).filter((e): e is IndexEntry => !!e)
}

// Deterministic string hash (djb2) for stable distractor selection.
function hash(s: string): number {
  let h = 5381
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) | 0
  return Math.abs(h)
}

function getUnitId(u: AuthoredUnit): string {
  return `${u.level.toLowerCase()}-u${String(u.order).padStart(2, "0")}`
}

function pickDistractors(pool: string[], exclude: Set<string>, seed: string, n: number): string[] {
  const out: string[] = []
  const start = hash(seed) % pool.length
  for (let i = 0; i < pool.length && out.length < n; i++) {
    const candidate = pool[(start + i) % pool.length]
    if (candidate && !exclude.has(candidate) && !out.includes(candidate)) out.push(candidate)
  }
  return out
}

const opts = (labels: string[]): QuizOption[] => labels.map((label, i) => ({ id: `opt_${i}`, label }))

/** Convert an authored question into a quiz-renderer-compatible payload. */
function buildQuestion(id: string, q: AuthoredQuestion): QuizQuestion {
  const base = { id, points: q.points ?? 1, explanation: q.explain }
  switch (q.kind) {
    case "mcq": {
      if (q.answer < 0 || q.answer >= q.options.length) throw new Error(`mcq answer index out of range: ${q.text}`)
      const correct = q.options[q.answer]!
      const distractors = q.options.filter((_, i) => i !== q.answer)
      return { ...base, type: "single", text: q.text, options: opts([correct, ...distractors]), answer: "opt_0" }
    }
    case "multi": {
      const correct = q.answers.map((i) => q.options[i]!)
      const distractors = q.options.filter((_, i) => !q.answers.includes(i))
      return {
        ...base,
        type: "multiple",
        text: q.text,
        options: opts([...correct, ...distractors]),
        answers: correct.map((_, i) => `opt_${i}`),
      }
    }
    case "tf":
      return { ...base, type: "true-false", text: q.text, answer: q.answer }
    case "short":
      return { ...base, type: "short-answer", text: q.text, answer: q.accept[0], accept: q.accept }
    case "order": {
      const items = opts(q.tokens)
      return { ...base, type: "ordering", text: q.text, items, correctOrder: items.map((o) => o.id) }
    }
    case "blank": {
      let text = q.text
      for (const _b of q.blanks) text = text.replace("___", "{{blank}}")
      if (text.includes("___")) throw new Error(`blank question has more ___ than answers: ${q.text}`)
      return { ...base, type: "fill-blank", text, caseInsensitive: true, blankAnswers: q.blanks }
    }
    case "match": {
      const prompts = opts(q.pairs.map((p) => p[0]))
      const responses = opts([...q.pairs.map((p) => p[1]), ...(q.extra ?? [])])
      const pairMap: Record<string, string> = {}
      q.pairs.forEach((_p, i) => {
        pairMap[`opt_${i}`] = `opt_${i}`
      })
      return { ...base, type: "matching", text: q.text, prompts, responses, pairMap }
    }
  }
}

type KanjiInfo = { meanings: string[]; onyomi: string[]; kunyomi: string[] }
type Pool = { glosses: string[]; kanji: Map<string, KanjiInfo> }

async function buildPools(units: AuthoredUnit[]): Promise<Map<Level, Pool>> {
  const pools = new Map<Level, Pool>()
  for (const level of ["N5", "N4", "N3", "N2", "N1"] as const) {
    const levelUnits = units.filter((u) => u.level === level)
    if (!levelUnits.length) continue
    const glosses = [
      ...new Set(
        levelUnits
          .flatMap((u) => resolveVocab(u.vocab, getUnitId(u)))
          .map((e) => e.gloss)
          .filter(Boolean),
      ),
    ]
    const chars = [...new Set(levelUnits.flatMap((u) => u.kanji))]
    const kanjiRows = await prisma.kanji.findMany({
      where: { char: { in: chars } },
      select: { char: true, meanings: true, onyomi: true, kunyomi: true },
    })
    const kanji = new Map(
      kanjiRows.map((k) => [
        k.char,
        {
          meanings: ((k.meanings as string[]) ?? []).filter(Boolean),
          onyomi: ((k.onyomi as string[]) ?? []).filter(Boolean),
          kunyomi: ((k.kunyomi as string[]) ?? []).filter(Boolean),
        },
      ]),
    )
    pools.set(level, { glosses, kanji })
  }
  return pools
}

function vocabQuizzes(unit: AuthoredUnit, pool: Pool): QuizQuestion[] {
  const out: QuizQuestion[] = []
  const entries = resolveVocab(unit.vocab, getUnitId(unit))
  entries.forEach((entry, i) => {
    const display = entry.kanji || entry.kana
    // Recognition: JP → EN
    const distractors = pickDistractors(pool.glosses, new Set([entry.gloss]), entry.id + "r", 3)
    if (distractors.length === 3) {
      out.push({
        id: `${getUnitId(unit)}-vrec-${i}`,
        type: "single",
        text: `What does **${display}${entry.kana !== display ? ` (${entry.kana})` : ""}** mean?`,
        points: 1,
        options: opts([entry.gloss, ...distractors]),
        answer: "opt_0",
      })
    }
    // Recall: EN → JP
    const accept = [entry.kanji, entry.kana].filter(Boolean)
    if (accept.length) {
      out.push({
        id: `${getUnitId(unit)}-vrecal-${i}`,
        type: "short-answer",
        text: `How do you say **${entry.gloss}** in Japanese? (kana is fine)`,
        points: 1,
        answer: accept[0],
        accept,
      })
    }
  })
  return out
}

function kanjiQuizzes(unit: AuthoredUnit, pool: Pool): QuizQuestion[] {
  const out: QuizQuestion[] = []
  const allMeanings = [...pool.kanji.values()].flatMap((k) => k.meanings)
  const allReadings = [...pool.kanji.values()].flatMap((k) => [...k.onyomi, ...k.kunyomi])
  unit.kanji.forEach((char, i) => {
    const k = pool.kanji.get(char)
    if (!k) return
    const meaning = k.meanings.slice(0, 2).join(", ")
    if (meaning) {
      const distractors = pickDistractors(allMeanings, new Set(k.meanings), char + "m", 3)
      if (distractors.length === 3) {
        out.push({
          id: `${getUnitId(unit)}-km-${i}`,
          type: "single",
          text: `What does the kanji **${char}** mean?`,
          points: 1,
          options: opts([meaning, ...distractors]),
          answer: "opt_0",
        })
      }
    }
    const reading = k.onyomi[0] ?? k.kunyomi[0]
    if (reading) {
      const distractors = pickDistractors(allReadings, new Set([...k.onyomi, ...k.kunyomi]), char + "r", 3)
      if (distractors.length === 3) {
        out.push({
          id: `${getUnitId(unit)}-kr-${i}`,
          type: "single",
          text: `Which is a reading of **${char}**?`,
          points: 1,
          options: opts([reading, ...distractors]),
          answer: "opt_0",
        })
      }
    }
  })
  return out
}

/** Compose the unit exam: lesson items + vocab + kanji, deterministically ordered. */
function composeExam(unit: AuthoredUnit, lessonItems: QuizQuestion[][], pool: Pool): QuizQuestion[] {
  const parts: QuizQuestion[] = []
  for (const items of lessonItems) parts.push(...items.slice(0, 2))
  const vrec = vocabQuizzes(unit, pool).filter((q) => q.id.includes("-vrec-"))
  for (let i = 0; i < vrec.length; i += 4) parts.push(vrec[i]!)
  const kq = kanjiQuizzes(unit, pool)
  parts.push(...kq.filter((q) => q.id.includes("-km-")).slice(0, 2))
  parts.push(...kq.filter((q) => q.id.includes("-kr-")).slice(0, 1))
  parts.push(...(unit.exam ?? []).map((q, i) => buildQuestion(`${getUnitId(unit)}-ex-${i}`, q)))

  // deterministic shuffle by unit id, then cap at 15
  const arr = [...parts]
  for (let i = arr.length - 1; i > 0; i--) {
    const j = (hash(getUnitId(unit) + ":" + i) % (i + 1) + i) % (i + 1)
    ;[arr[i], arr[j]] = [arr[j]!, arr[i]!]
  }
  return arr.slice(0, 15)
}

async function main() {
  const units: AuthoredUnit[] = []
  let invalid = 0
  for (const raw of CURRICULUM) {
    const parsed = AuthoredUnitSchema.safeParse(raw)
    if (!parsed.success) {
      invalid++
      console.error(`INVALID UNIT ${raw.level} #${raw.order}:`, parsed.error.issues.slice(0, 4))
    } else {
      units.push(parsed.data)
    }
  }
  if (invalid) {
    console.error(`${invalid} invalid units — aborting`)
    process.exit(1)
  }
  console.log(`Validated ${units.length} units`)

  const pools = await buildPools(units)

  for (const unit of units) {
    for (const lesson of unit.lessons) {
      for (const ex of lesson.examples) {
        if (!alignFurigana(ex.jp, ex.kana)) {
          console.warn(`[furigana] ${lesson.slug}: cannot align "${ex.jp}" / "${ex.kana}"`)
        }
      }
    }
  }

  const counts = { units: 0, lessons: 0, examples: 0, items: 0, vocab: 0, kanji: 0, examItems: 0 }

  for (const unit of units) {
    await prisma.unit.upsert({
      where: { id: getUnitId(unit) },
      create: { id: getUnitId(unit), level: unit.level, order: unit.order, title: unit.title, titleJp: unit.titleJp, description: unit.description },
      update: { level: unit.level, order: unit.order, title: unit.title, titleJp: unit.titleJp, description: unit.description },
    })
    counts.units++

    const lessonItems: QuizQuestion[][] = []
    for (let li = 0; li < unit.lessons.length; li++) {
      const lesson = unit.lessons[li]!
      await prisma.lesson.upsert({
        where: { id: lesson.slug },
        create: {
          id: lesson.slug,
          unitId: getUnitId(unit),
          order: li + 1,
          title: lesson.title,
          titleJp: lesson.titleJp,
          grammarLabel: lesson.grammarLabel,
          summary: lesson.summary,
          body: lesson.body,
        },
        update: {
          unitId: getUnitId(unit),
          order: li + 1,
          title: lesson.title,
          titleJp: lesson.titleJp,
          grammarLabel: lesson.grammarLabel,
          summary: lesson.summary,
          body: lesson.body,
        },
      })
      counts.lessons++

      await prisma.example.deleteMany({ where: { lessonId: lesson.slug } })
      const exampleRows = lesson.examples.map((ex, ei) => ({
        lessonId: lesson.slug,
        order: ei + 1,
        jp: ex.jp,
        kana: ex.kana,
        romaji: toRomaji(ex.kana),
        en: ex.en,
        note: ex.note,
        segments: alignFurigana(ex.jp, ex.kana) ?? [],
      }))
      await prisma.example.createMany({ data: exampleRows })
      counts.examples += exampleRows.length

      await prisma.quizItem.deleteMany({ where: { lessonId: lesson.slug, scope: "LESSON_PRACTICE" } })
      const items = lesson.practice.map((q, qi) => buildQuestion(`${lesson.slug}-p${qi + 1}`, q))
      await prisma.quizItem.createMany({
        data: items.map((payload, qi) => ({
          scope: "LESSON_PRACTICE" as const,
          lessonId: lesson.slug,
          unitId: getUnitId(unit),
          order: qi + 1,
          type: payload.type,
          payload,
          points: payload.points,
        })),
      })
      counts.items += items.length
      lessonItems.push(items)
    }

    // Vocab
    await prisma.unitVocab.deleteMany({ where: { unitId: getUnitId(unit) } })
    const pool = pools.get(unit.level)!
    const entries = resolveVocab(unit.vocab, getUnitId(unit))
    if (entries.length) {
      await prisma.unitVocab.createMany({
        data: entries.map((entry, vi) => ({ unitId: getUnitId(unit), wordId: entry.id, order: vi + 1 })),
      })
      counts.vocab += entries.length
    }

    // Kanji allocation
    for (const char of unit.kanji) {
      try {
        await prisma.kanji.update({ where: { char }, data: { level: unit.level, unitId: getUnitId(unit) } })
        counts.kanji++
      } catch {
        console.warn(`[kanji] ${getUnitId(unit)}: ${char} not found in Kanji table`)
      }
    }

    // Vocab + kanji practice items
    await prisma.quizItem.deleteMany({ where: { unitId: getUnitId(unit), scope: "VOCAB_PRACTICE" } })
    const vq = [...vocabQuizzes(unit, pool), ...kanjiQuizzes(unit, pool)]
    if (vq.length) {
      await prisma.quizItem.createMany({
        data: vq.map((payload, qi) => ({
          scope: "VOCAB_PRACTICE" as const,
          unitId: getUnitId(unit),
          order: qi + 1,
          type: payload.type,
          payload,
          points: payload.points,
        })),
      })
      counts.items += vq.length
    }

    // Unit exam
    await prisma.quizItem.deleteMany({ where: { unitId: getUnitId(unit), scope: "UNIT_EXAM" } })
    const exam = composeExam(unit, lessonItems, pool)
    await prisma.quizItem.createMany({
      data: exam.map((payload, qi) => ({
        scope: "UNIT_EXAM" as const,
        unitId: getUnitId(unit),
        order: qi + 1,
        type: payload.type,
        payload,
        points: payload.points,
      })),
    })
    counts.examItems += exam.length

    console.log(`Seeded ${getUnitId(unit)} — ${unit.lessons.length} lessons, ${entries.length} vocab, ${unit.kanji.length} kanji, exam ${exam.length}`)
  }

  // Clean up stale SRS cards whose references no longer exist
  // (e.g. quiz items recreated with new IDs after a reseed).
  const grammarIds = new Set((await prisma.quizItem.findMany({ select: { id: true } })).map((q) => q.id))
  const wordIds = new Set((await prisma.word.findMany({ select: { id: true } })).map((w) => w.id))
  const kanjiChars = new Set((await prisma.kanji.findMany({ select: { char: true } })).map((k) => k.char))
  const staleCards = await prisma.srsCard.findMany({ select: { id: true, cardType: true, refId: true } })
  const stale = staleCards.filter((c) => {
    if (c.cardType === "GRAMMAR_CLOZE") return !grammarIds.has(c.refId)
    if (c.cardType === "VOCAB_RECOG" || c.cardType === "VOCAB_RECALL") return !wordIds.has(c.refId)
    return !kanjiChars.has(c.refId)
  })
  if (stale.length) {
    await prisma.srsCard.deleteMany({ where: { id: { in: stale.map((c) => c.id) } } })
    console.log(`Removed ${stale.length} stale SRS cards`)
  }

  console.log("Counts:", counts)
}

main()
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
